### ISSUE TITLE
How to clean the clipboard of Here?

### ISSUE THREAD

**Issue by StayTherapy** [hereappdev/Here-Plugins#26]
clipboard of Here is useful but how can I clean or delete some item like password from clipboard list?

**Comment by hereappdev** [comment]
Now you can only remove the whole list. Remove individual items is not supported currently.
![image](https://user-images.githubusercontent.com/46374620/128479709-a88807b5-cbd0-4e71-9e4c-416b898a7018.png)

**Comment by StayTherapy** [comment]
> Now you can only remove the whole list. Remove individual items is not supported currently.
> ![image](https://user-images.githubusercontent.com/46374620/128479709-a88807b5-cbd0-4e71-9e4c-416b898a7018.png)

@hereappdev Thanks  for your replay, but how can i open the `clear ..` menu ? 😄

My App info:
`buildNumber: 2164`
`shortVersion: 0.12.0`
`versionString: v0.12.0 (2164)`

**Comment by StayTherapy** [comment]
Find it. The Clipboard clear menu is at the bottom.
